Add error handling to create_raid_array, and add hashbang to check_gpu.sh

diff --git a/create_raid_array b/create_raid_array
--- a/create_raid_array
+++ b/create_raid_array
@@ -1,5 +1,9 @@
 #!/bin/bash
 set -e
+err_report() {
+  echo "Error at $BASH_SOURCE on line $1!"
+}
+trap 'err_report $LINENO' ERR
 
 if [[ "$EUID" != "0" ]]; then
   echo "Must be run as root!"
